import { GithubUser } from "./github-user.interface";

// Generated by https://quicktype.io

export interface GithubUsersResponse {
    total_count:        number;
    incomplete_results: boolean;
    items:              GithubUser[];
}
